### ISSUE TITLE
GHFileNotFoundException because of wrong parsed repository name

### ISSUE THREAD

**Issue by mibo** [SAP/fosstars-rating-core#213]
It looks like during parse of a git scm url which ends with `.git` (in `com.sap.sgs.phosphor.fosstars.tool.github.GitHubProject#parse`) the name of the repository ends with `.git`.
This leads to problems if later the Github API is used as the repositories are identified without `.git` (which is only used for direct git commands e.g. `git clone ...`).

See also below stack trace.

```
2020-06-03T11:43:18.90+0200 [APP/PROC/WEB/0] OUT org.kohsuke.github.GHFileNotFoundException: https://api.github.com/repos/resilience4j/resilience4j.git {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/#get"}
   2020-06-03T11:43:18.90+0200 [APP/PROC/WEB/0] OUT 	at org.kohsuke.github.GitHubClient.interpretApiError(GitHubClient.java:437) ~[github-api-1.109.jar:na]
   2020-06-03T11:43:18.90+0200 [APP/PROC/WEB/0] OUT 	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:368) ~[github-api-1.109.jar:na]
   2020-06-03T11:43:18.90+0200 [APP/PROC/WEB/0] OUT 	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:312) ~[github-api-1.109.jar:na]
   2020-06-03T11:43:18.90+0200 [APP/PROC/WEB/0] OUT 	at org.kohsuke.github.Requester.fetch(Requester.java:71) ~[github-api-1.109.jar:na]
   2020-06-03T11:43:18.90+0200 [APP/PROC/WEB/0] OUT 	at org.kohsuke.github.GitHub.getRepository(GitHub.java:531) ~[github-api-1.109.jar:na]
   2020-06-03T11:43:18.90+0200 [APP/PROC/WEB/0] OUT 	at com.sap.sgs.phosphor.fosstars.data.github.GitHubDataFetcher.repositoryFor(GitHubDataFetcher.java:168) ~[fosstars-rating-core-0.7.1-HOWLER.jar:na]
```

**Comment by mibo** [comment]
Hope this is not a duplicate (at least I did not found a similar issue).
If it is a new issue I can volunteer to fix it (next week?).

**Comment by artem-smotrakov** [comment]
@mibo Thanks for reporting this. Looks like a bug. Feel free to open a pull request when you have time.
