### ISSUE TITLE
OssSecurityRating deserialization fails

### ISSUE THREAD

**Issue by artem-smotrakov** [SAP/fosstars-rating-core#439]
```java
OssSecurityRating rating = RatingRepository.INSTANCE.rating(OssSecurityRating.class);
Json.read(Json.toBytes(rating), OssSecurityRating.class)
```

This code throws the following exception:

```
com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `com.sap.oss.phosphor.fosstars.model.rating.oss.OssSecurityRating`, problem: Oh no! Thresholds is null!
 at [Source: (byte[])"{
  "type" : "OssSecurityRating",
  "score" : {
    "type" : "OssSecurityScore",
    "name" : "Security score for open-source projects",
    "subScores" : [ {
      "type" : "ProjectSecurityAwarenessScore",
      "name" : "How well open-source community is aware about security"
    }, {
      "type" : "UnpatchedVulnerabilitiesScore",
      "name" : "How well vulnerabilities are patched"
    }, {
      "type" : "VulnerabilityDiscoveryAndSecurityTestingScore",
      "securityTestingScore" : {
    "[truncated 6732 bytes]; line: 198, column: 1]

	at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1907)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:587)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:610)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:293)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:288)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:520)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1390)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:230)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:197)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:135)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:105)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1277)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3609)
	at com.sap.oss.phosphor.fosstars.util.Json.read(Json.java:42)
	at com.sap.oss.phosphor.fosstars.model.rating.oss.OssSecurityRatingTest.testRatingJsonSerialization(OssSecurityRatingTest.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:114)
Caused by: java.lang.NullPointerException: Oh no! Thresholds is null!
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.sap.oss.phosphor.fosstars.model.rating.oss.OssSecurityRating.<init>(OssSecurityRating.java:51)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:291)
	... 46 more
```

**Comment by artem-smotrakov** [comment]
Draft patch:

```
diff --git a/src/main/java/com/sap/oss/phosphor/fosstars/model/rating/oss/OssSecurityRating.java b/src/main/java/com/sap/oss/phosphor/fosstars/model/rating/oss/OssSecurityRating.java
index b7203555..8c6eca3d 100644
--- a/src/main/java/com/sap/oss/phosphor/fosstars/model/rating/oss/OssSecurityRating.java
+++ b/src/main/java/com/sap/oss/phosphor/fosstars/model/rating/oss/OssSecurityRating.java
@@ -1,6 +1,7 @@
 package com.sap.oss.phosphor.fosstars.model.rating.oss;
 
 import com.fasterxml.jackson.annotation.JsonCreator;
+import com.fasterxml.jackson.annotation.JsonGetter;
 import com.fasterxml.jackson.annotation.JsonProperty;
 import com.sap.oss.phosphor.fosstars.model.Confidence;
 import com.sap.oss.phosphor.fosstars.model.Label;
@@ -83,6 +84,7 @@ public class OssSecurityRating extends AbstractRating {
    *
    * @return The thresholds for the labels.
    */
+  @JsonGetter("thresholds")
   public Thresholds thresholds() {
     return thresholds;
   }
@@ -144,6 +146,7 @@ public class OssSecurityRating extends AbstractRating {
      *
      * @return The threshold.
      */
+    @JsonGetter("moderate")
     public double forModerate() {
       return moderate;
     }
@@ -153,6 +156,7 @@ public class OssSecurityRating extends AbstractRating {
      *
      * @return The threshold.
      */
+    @JsonGetter("good")
     public double forGood() {
       return good;
     }
@@ -162,9 +166,29 @@ public class OssSecurityRating extends AbstractRating {
      *
      * @return The threshold.
      */
+    @JsonGetter("unclear")
     public double forUnclear() {
       return unclear;
     }
+
+    @Override
+    public boolean equals(Object o) {
+      if (this == o) {
+        return true;
+      }
+      if (o instanceof Thresholds == false) {
+        return false;
+      }
+      Thresholds that = (Thresholds) o;
+      return Double.compare(that.moderate, moderate) == 0
+          && Double.compare(that.good, good) == 0
+          && Double.compare(that.unclear, unclear) == 0;
+    }
+
+    @Override
+    public int hashCode() {
+      return Objects.hash(moderate, good, unclear);
+    }
   }
 
 }
```

Need to add tests.
