### ISSUE TITLE
OssSecurityRatingMarkdownReporter fails to deserialize data

### ISSUE THREAD

**Issue by artem-smotrakov** [SAP/fosstars-rating-core#546]
While creating a report with a config, the command-line tool fails to load data:

```
[+] Loading config from docs/oss/security/spring.yml
[x] Something went wrong!
com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve subtype of [simple type, class com.sap.oss.phosphor.fosstars.model.subject.oss.GitHubProject]: missing type id property 'type'
 at [Source: (sun.nio.ch.ChannelInputStream); line: 9598, column: 1] (through reference chain: java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
	at com.fasterxml.jackson.databind.DeserializationContext.missingTypeIdException(DeserializationContext.java:1943)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingTypeId(DeserializationContext.java:1456)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleMissingTypeId(TypeDeserializerBase.java:307)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:178)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:115)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1292)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:357)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3593)
	at com.sap.oss.phosphor.fosstars.tool.github.AbstractReporter.loadProjects(AbstractReporter.java:103)
	at com.sap.oss.phosphor.fosstars.tool.github.AbstractReporter.loadProjects(AbstractReporter.java:83)
	at com.sap.oss.phosphor.fosstars.tool.github.OssSecurityRatingMarkdownReporter.<init>(OssSecurityRatingMarkdownReporter.java:149)
	at com.sap.oss.phosphor.fosstars.tool.github.Application.reporterFrom(Application.java:683)
	at com.sap.oss.phosphor.fosstars.tool.github.Application.makeReporters(Application.java:662)
	at com.sap.oss.phosphor.fosstars.tool.github.Application.processConfig(Application.java:477)
	at com.sap.oss.phosphor.fosstars.tool.github.Application.run(Application.java:356)
	at com.sap.oss.phosphor.fosstars.tool.github.Application.main(Application.java:160)
```

**Comment by artem-smotrakov** [comment]
It happens because Jackson can't get actual types if a generic list is used, see https://github.com/FasterXML/jackson-databind/issues/2185
