### ISSUE TITLE
OOM when loading commits in LocalRepository

### ISSUE THREAD

**Issue by artem-smotrakov** [SAP/fosstars-rating-core#647]
A data provider that examines a project's commit history can fail with OOM if the history is long:

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.eclipse.jgit.internal.storage.file.PackIndexV2.<init>(PackIndexV2.java:95)
	at org.eclipse.jgit.internal.storage.file.PackIndex.read(PackIndex.java:101)
	at org.eclipse.jgit.internal.storage.file.PackIndex.open(PackIndex.java:67)
	at org.eclipse.jgit.internal.storage.file.Pack.idx(Pack.java:161)
	at org.eclipse.jgit.internal.storage.file.Pack.get(Pack.java:273)
	at org.eclipse.jgit.internal.storage.file.PackDirectory.open(PackDirectory.java:211)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openPackedObject(ObjectDirectory.java:390)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openPackedFromSelfOrAlternate(ObjectDirectory.java:354)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObjectWithoutRestoring(ObjectDirectory.java:345)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObject(ObjectDirectory.java:330)
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:132)
	at org.eclipse.jgit.revwalk.RevWalk.getCachedBytes(RevWalk.java:1109)
	at org.eclipse.jgit.revwalk.RevCommit.parseHeaders(RevCommit.java:126)
	at org.eclipse.jgit.revwalk.RevWalk.markStart(RevWalk.java:308)
	at org.eclipse.jgit.api.LogCommand.add(LogCommand.java:343)
	at org.eclipse.jgit.api.LogCommand.add(LogCommand.java:180)
	at org.eclipse.jgit.api.LogCommand.call(LogCommand.java:133)
	at com.sap.oss.phosphor.fosstars.data.github.LocalRepository.loadCommitsIfNecessary(LocalRepository.java:348)
	at com.sap.oss.phosphor.fosstars.data.github.LocalRepository.commitsAfter(LocalRepository.java:100)
	at com.sap.oss.phosphor.fosstars.data.github.NumberOfContributors.fetchValueFor(NumberOfContributors.java:47)
	at com.sap.oss.phosphor.fosstars.data.github.CachedSingleFeatureGitHubDataProvider.fetchValuesFor(CachedSingleFeatureGitHubDataProvider.java:30)
	at com.sap.oss.phosphor.fosstars.data.github.GitHubCachingDataProvider.fetchValuesFor(GitHubCachingDataProvider.java:45)
	at com.sap.oss.phosphor.fosstars.data.AbstractCachingDataProvider.doUpdate(AbstractCachingDataProvider.java:63)
	at com.sap.oss.phosphor.fosstars.data.AbstractCachingDataProvider.doUpdate(AbstractCachingDataProvider.java:20)
	at com.sap.oss.phosphor.fosstars.data.AbstractDataProvider.update(AbstractDataProvider.java:74)
	at com.sap.oss.phosphor.fosstars.data.AbstractDataProvider.update(AbstractDataProvider.java:18)
	at com.sap.oss.phosphor.fosstars.tool.SingleRatingCalculator.calculateFor(SingleRatingCalculator.java:113)
	at com.sap.oss.phosphor.fosstars.tool.SingleRatingCalculator.calculateFor(SingleRatingCalculator.java:23)
	at com.sap.oss.phosphor.fosstars.tool.MultipleRatingsCalculator.calculateFor(MultipleRatingsCalculator.java:110)
	at com.sap.oss.phosphor.fosstars.tool.MultipleRatingsCalculator.calculateFor(MultipleRatingsCalculator.java:142)
	at com.sap.oss.phosphor.fosstars.tool.AbstractHandler.processConfig(AbstractHandler.java:363)
	at com.sap.oss.phosphor.fosstars.tool.AbstractHandler$$Lambda$33/1231799381.run(Unknown Source)
```

**Comment by artem-smotrakov** [comment]
Another OOM can occur while cloning a repository:

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.eclipse.jgit.internal.storage.pack.BinaryDelta.apply(BinaryDelta.java:130)
	at org.eclipse.jgit.internal.storage.pack.BinaryDelta.apply(BinaryDelta.java:85)
	at org.eclipse.jgit.transport.PackParser.resolveDeltas(PackParser.java:664)
	at org.eclipse.jgit.transport.PackParser.resolveDeltas(PackParser.java:640)
	at org.eclipse.jgit.transport.PackParser.resolveDeltas(PackParser.java:603)
	at org.eclipse.jgit.transport.PackParser.processDeltas(PackParser.java:580)
	at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:551)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryPackParser.parse(ObjectDirectoryPackParser.java:169)
	at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:496)
	at org.eclipse.jgit.transport.BasePackFetchConnection.receivePack(BasePackFetchConnection.java:1017)
	at org.eclipse.jgit.transport.BasePackFetchConnection.doFetchV2(BasePackFetchConnection.java:469)
	at org.eclipse.jgit.transport.BasePackFetchConnection.doFetch(BasePackFetchConnection.java:376)
	at org.eclipse.jgit.transport.TransportHttp$SmartHttpFetchConnection.doFetch(TransportHttp.java:1550)
	at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:302)
	at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:293)
	at org.eclipse.jgit.transport.FetchProcess.fetchObjects(FetchProcess.java:274)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:171)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:94)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1309)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:213)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:303)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:178)
	at com.sap.oss.phosphor.fosstars.data.github.GitHubDataFetcher.clone(GitHubDataFetcher.java:404)
	at com.sap.oss.phosphor.fosstars.data.github.GitHubDataFetcher.loadLocalRepositoryFor(GitHubDataFetcher.java:334)
	at com.sap.oss.phosphor.fosstars.data.github.GitHubDataFetcher.localRepositoryFor(GitHubDataFetcher.java:300)
	at com.sap.oss.phosphor.fosstars.data.github.CodeqlDataProvider.fetchValuesFor(CodeqlDataProvider.java:73)
	at com.sap.oss.phosphor.fosstars.data.github.GitHubCachingDataProvider.fetchValuesFor(GitHubCachingDataProvider.java:45)
	at com.sap.oss.phosphor.fosstars.data.AbstractCachingDataProvider.doUpdate(AbstractCachingDataProvider.java:63)
	at com.sap.oss.phosphor.fosstars.data.AbstractCachingDataProvider.doUpdate(AbstractCachingDataProvider.java:20)
	at com.sap.oss.phosphor.fosstars.data.AbstractDataProvider.update(AbstractDataProvider.java:74)
	at com.sap.oss.phosphor.fosstars.data.AbstractDataProvider.update(AbstractDataProvider.java:18)
	at com.sap.oss.phosphor.fosstars.tool.SingleRatingCalculator.calculateFor(SingleRatingCalculator.java:113)
```
