### ISSUE TITLE
Insufficient Java heap space issue during OSS project report generation

### ISSUE THREAD

**Issue by sourabhsparkala** [SAP/fosstars-rating-core#667]
While running the report generation GitHub action https://github.com/SAP/fosstars-rating-core/runs/3229566505?check_suite_focus=true

We are facing an Insufficient Java heap space issue

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.eclipse.jgit.internal.storage.pack.BinaryDelta.apply(BinaryDelta.java:130)
	at org.eclipse.jgit.internal.storage.pack.BinaryDelta.apply(BinaryDelta.java:85)
	at org.eclipse.jgit.transport.PackParser.resolveDeltas(PackParser.java:664)
	at org.eclipse.jgit.transport.PackParser.resolveDeltas(PackParser.java:640)
	at org.eclipse.jgit.transport.PackParser.resolveDeltas(PackParser.java:603)
	at org.eclipse.jgit.transport.PackParser.processDeltas(PackParser.java:580)
	at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:551)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryPackParser.parse(ObjectDirectoryPackParser.java:169)
	at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:496)
	at org.eclipse.jgit.transport.BasePackFetchConnection.receivePack(BasePackFetchConnection.java:1017)
	at org.eclipse.jgit.transport.BasePackFetchConnection.doFetchV2(BasePackFetchConnection.java:469)
	at org.eclipse.jgit.transport.BasePackFetchConnection.doFetch(BasePackFetchConnection.java:376)
	at org.eclipse.jgit.transport.TransportHttp$SmartHttpFetchConnection.doFetch(TransportHttp.java:1550)
	at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:302)
	at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:293)
	at org.eclipse.jgit.transport.FetchProcess.fetchObjects(FetchProcess.java:274)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:171)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:94)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1309)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:213)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:303)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:178)
	at com.sap.oss.phosphor.fosstars.data.github.GitHubDataFetcher.clone(GitHubDataFetcher.java:404)
	at com.sap.oss.phosphor.fosstars.data.github.GitHubDataFetcher.loadLocalRepositoryFor(GitHubDataFetcher.java:334)
	at com.sap.oss.phosphor.fosstars.data.github.GitHubDataFetcher.localRepositoryFor(GitHubDataFetcher.java:300)
	at com.sap.oss.phosphor.fosstars.data.github.CodeqlDataProvider.fetchValuesFor(CodeqlDataProvider.java:73)
	at com.sap.oss.phosphor.fosstars.data.github.GitHubCachingDataProvider.fetchValuesFor(GitHubCachingDataProvider.java:45)
	at com.sap.oss.phosphor.fosstars.data.AbstractCachingDataProvider.doUpdate(AbstractCachingDataProvider.java:63)
	at com.sap.oss.phosphor.fosstars.data.AbstractCachingDataProvider.doUpdate(AbstractCachingDataProvider.java:20)
	at com.sap.oss.phosphor.fosstars.data.AbstractDataProvider.update(AbstractDataProvider.java:74)
	at com.sap.oss.phosphor.fosstars.data.AbstractDataProvider.update(AbstractDataProvider.java:18)
	at com.sap.oss.phosphor.fosstars.tool.SingleRatingCalculator.calculateFor(SingleRatingCalculator.java:131)
```

DOD:
- The report generation script should run without such issues

**Comment by sourabhsparkala** [comment]
We have to test with few options
- ´Xms´ option during report generation step https://github.com/SAP/fosstars-rating-core/blob/master/.github/actions/project-security-report-action/entrypoint.sh#L53
- To do step 1, we need to check if we can configure Docker image memory
- If the above steps are not available, maybe we need to get rid of loading the entire NVD
