### ISSUE TITLE
CLI test check issue for one of the OSSF review PURL syntax check

### ISSUE THREAD

**Issue by sourabhsparkala** [SAP/fosstars-rating-core#753]
Facing this issue while running CLI test checks in github. Although it does not actually affect the rating-core working. The issue is with the [https://github.com/ossf/security-reviews/blob/main/reviews/github/standardnotes/snjs-sncrypto.md](standardnotes/snjs-sncrypto.md). There is a Malformed Purl syntax. Hence this issue.

```
[+] fosstars-rating-core/.fosstars/repositories/ossf/security-reviews/reviews/github/standardnotes/snjs-sncrypto.md
[!] Oops! Could not parse package URL: pkg:pkg:github.com/standardnotes/snjs
com.github.packageurl.MalformedPackageURLException: The PackageURL type contains invalid characters
	at com.github.packageurl.PackageURL.validateType(PackageURL.java:244)
	at com.github.packageurl.PackageURL.parse(PackageURL.java:527)
	at com.github.packageurl.PackageURL.<init>(PackageURL.java:68)
	at com.sap.oss.phosphor.fosstars.data.github.SecurityReviewsFromOpenSSF.purlBelongsTo(SecurityReviewsFromOpenSSF.java:164)
	at com.sap.oss.phosphor.fosstars.data.github.SecurityReviewsFromOpenSSF.lambda$isReviewFor$4(SecurityReviewsFromOpenSSF.java:152)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at com.sap.oss.phosphor.fosstars.data.github.SecurityReviewsFromOpenSSF.isReviewFor(SecurityReviewsFromOpenSSF.java:152)
	at com.sap.oss.phosphor.fosstars.data.github.SecurityReviewsFromOpenSSF.fetchValueFor(SecurityReviewsFromOpenSSF.java:98)
	at com.sap.oss.phosphor.fosstars.data.github.CachedSingleFeatureGitHubDataProvider.fetchValuesFor(CachedSingleFeatureGitHubDataProvider.java:30)
	at com.sap.oss.phosphor.fosstars.data.github.GitHubCachingDataProvider.fetchValuesFor(GitHubCachingDataProvider.java:45)
	at com.sap.oss.phosphor.fosstars.data.AbstractCachingDataProvider.doUpdate(AbstractCachingDataProvider.java:63)
	at com.sap.oss.phosphor.fosstars.data.AbstractCachingDataProvider.doUpdate(AbstractCachingDataProvider.java:20)
	at com.sap.oss.phosphor.fosstars.data.AbstractDataProvider.update(AbstractDataProvider.java:74)
	at com.sap.oss.phosphor.fosstars.data.AbstractDataProvider.update(AbstractDataProvider.java:18)
	at com.sap.oss.phosphor.fosstars.tool.SingleRatingCalculator.calculateFor(SingleRatingCalculator.java:133)
	at com.sap.oss.phosphor.fosstars.tool.AbstractHandler.process(AbstractHandler.java:266)
	at com.sap.oss.phosphor.fosstars.tool.AbstractHandler.processUrl(AbstractHandler.java:256)
	at com.sap.oss.phosphor.fosstars.tool.AbstractHandler.run(AbstractHandler.java:236)
	at com.sap.oss.phosphor.fosstars.tool.Application.run(Application.java:307)
	at com.sap.oss.phosphor.fosstars.tool.Application.main(Application.java:84)
```

Things to do:
- Fix this.

**Comment by sourabhsparkala** [comment]
Create a PR https://github.com/ossf/security-reviews/pull/66
