### ISSUE TITLE
OWASP Dependency check throws a Null Pointer Exception

### ISSUE THREAD

**Issue by sourabhsparkala** [SAP/fosstars-rating-core#883]
Sometimes when the NVD json download fails as a prestep for OWASP dependency check. A `null pointer exception` is thrown

```
[!] Holy Moly, VulnerabilitiesFromOwaspDependencyCheck data provider failed!
[!] The last thing that it said was
java.lang.NullPointerException
	at org.owasp.dependencycheck.Engine.writeReports(Engine.java:1189)
	at org.owasp.dependencycheck.Engine.writeReports(Engine.java:1143)
	at com.sap.oss.phosphor.fosstars.data.artifact.VulnerabilitiesFromOwaspDependencyCheck.process(VulnerabilitiesFromOwaspDependencyCheck.java:224)
	at com.sap.oss.phosphor.fosstars.data.artifact.VulnerabilitiesFromOwaspDependencyCheck.scan(VulnerabilitiesFromOwaspDependencyCheck.java:247)
	at com.sap.oss.phosphor.fosstars.data.artifact.VulnerabilitiesFromOwaspDependencyCheck.update(VulnerabilitiesFromOwaspDependencyCheck.java:156)
	at com.sap.oss.phosphor.fosstars.data.artifact.VulnerabilitiesFromOwaspDependencyCheck.update(VulnerabilitiesFromOwaspDependencyCheck.java:63)
	at com.sap.oss.phosphor.fosstars.tool.SingleRatingCalculator.calculateFor(SingleRatingCalculator.java:133)
	at com.sap.oss.phosphor.fosstars.tool.OssArtifactSecurityRatingHandler.processGav(OssArtifactSecurityRatingHandler.java:70)
	at com.sap.oss.phosphor.fosstars.tool.OssArtifactSecurityRatingHandler.processMaven(OssArtifactSecurityRatingHandler.java:49)
	at com.sap.oss.phosphor.fosstars.tool.AbstractHandler.run(AbstractHandler.java:236)
	at com.sap.oss.phosphor.fosstars.tool.Application.run(Application.java:307)
	at com.sap.oss.phosphor.fosstars.tool.Application.main(Application.java:84)
```

Things to do:
- Handle this situation `if the download fails` in a better way.

**Comment by sourabhsparkala** [comment]
There is no easy way to fix this issue.

OWASP dependency check downloads NVD cache to build its own DB (initialization of OWASP dependency check)
- The issue occurs when if downloading a NVD-yyyy file fails due to an unreachable server.

But I have tried to provide a fix in #914
