### ISSUE TITLE
Releases Maven throw 502 response code

### ISSUE THREAD

**Issue by sourabhsparkala** [SAP/fosstars-rating-core#908]
```
 java -jar target/fosstars-github-rating-calc.jar -r oss-artifact-security -t {token} -g org.bouncycastle:bcprov-jdk15on:1.59
[+] Okay, we have a GitHub token, let's try to use it
[x] Something went wrong!
java.io.IOException: Server returned HTTP response code: 502 for URL: https://search.maven.org/solrsearch/select?q=g:%22org.bouncycastle%22+AND+a:%22bcprov-jdk15on%22&core=gav&rows=20&wt=json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at java.net.URL.openStream(URL.java:1092)
	at com.fasterxml.jackson.core.TokenStreamFactory._optimizedStreamFromURL(TokenStreamFactory.java:211)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1055)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3125)
	at com.sap.oss.phosphor.fosstars.tool.MavenScmFinder.latestVersionOf(MavenScmFinder.java:218)
	at com.sap.oss.phosphor.fosstars.tool.MavenScmFinder.loadPomFor(MavenScmFinder.java:258)
	at com.sap.oss.phosphor.fosstars.tool.MavenScmFinder.findScmFor(MavenScmFinder.java:55)
	at com.sap.oss.phosphor.fosstars.tool.MavenScmFinder.findGithubProjectFor(MavenScmFinder.java:121)
	at com.sap.oss.phosphor.fosstars.tool.OssArtifactSecurityRatingHandler.processGav(OssArtifactSecurityRatingHandler.java:59)
	at com.sap.oss.phosphor.fosstars.tool.OssArtifactSecurityRatingHandler.processMaven(OssArtifactSecurityRatingHandler.java:49)
	at com.sap.oss.phosphor.fosstars.tool.AbstractHandler.run(AbstractHandler.java:236)
	at com.sap.oss.phosphor.fosstars.tool.Application.run(Application.java:307)
	at com.sap.oss.phosphor.fosstars.tool.Application.main(Application.java:84)
[x] Bye!
```
Things to do:
- The above exception should not halt the rating-core

**Comment by sourabhsparkala** [comment]
After a thorough investigation. 

The exception at this level makes sense. The whole rating core should not start if it cannot collect the associated repo for the given Maven Artifact.

Hence, this issue is subdued for now.
