### ISSUE TITLE
Build manual is outdated

### ISSUE THREAD

**Issue by halamix2** [SAP/fosstars-rating-core#993]
I was unable to build working .jar file using the provided instructions

```bash
java -version                                                                                                                                                    
openjdk version "21.0.2" 2024-01-16 LTS
OpenJDK Runtime Environment SapMachine (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM SapMachine (build 21.0.2+13-LTS, mixed mode, sharing)
```

<details>
    <summary>Compilation</summary>

```bash
git clone https://github.com/SAP/fosstars-rating-core.git
cd fosstars-rating-core
mvn package -DskipTests
```

```log
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------< com.sap.oss.phosphor:fosstars-rating-core >--------------
[INFO] Building Fosstars Rating Core 1.15.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] Parameter 'target' is unknown for plugin 'maven-javadoc-plugin:3.5.0:jar (attach-javadocs)'
[INFO] 
[INFO] --- jacoco:0.8.10:prepare-agent (default) @ fosstars-rating-core ---
[INFO] argLine set to -javaagent:~/.m2/repository/org/jacoco/org.jacoco.agent/0.8.10/org.jacoco.agent-0.8.10-runtime.jar=destfile=~/repos/fosstars-rating-core/target/jacoco.exec,append=true
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ fosstars-rating-core ---
[INFO] Copying 21 resources from src/main/resources to target/classes
[INFO] 
[INFO] --- compiler:3.11.0:compile (default-compile) @ fosstars-rating-core ---
[INFO] Changes detected - recompiling the module! :source
[INFO] Compiling 416 source files with javac [debug target 8] to target/classes
[WARNING] bootstrap class path not set in conjunction with -source 8
[WARNING] source value 8 is obsolete and will be removed in a future release
[WARNING] target value 8 is obsolete and will be removed in a future release
[WARNING] To suppress warnings about obsolete options, use -Xlint:-options.
[INFO] Annotation processing is enabled because one or more processors were found
  on the class path. A future release of javac may disable annotation processing
  unless at least one processor is specified by name (-processor), or a search
  path is specified (--processor-path, --processor-module-path), or annotation
  processing is enabled explicitly (-proc:only, -proc:full).
  Use -Xlint:-options to suppress this message.
  Use -proc:none to disable annotation processing.
[WARNING] ~/repos/fosstars-rating-core/src/main/java/com/sap/oss/phosphor/fosstars/tool/format/MarkdownTemplate.java:[44,36] non-varargs call of varargs method with inexact argument type for last parameter;
  cast to java.lang.Object for a varargs call
  cast to java.lang.Object[] for a non-varargs call and to suppress this warning
[INFO] ~/repos/fosstars-rating-core/src/main/java/com/sap/oss/phosphor/fosstars/tool/InputURL.java: Some input files use or override a deprecated API.
[INFO] ~/repos/fosstars-rating-core/src/main/java/com/sap/oss/phosphor/fosstars/tool/InputURL.java: Recompile with -Xlint:deprecation for details.
[INFO] ~/repos/fosstars-rating-core/src/main/java/com/sap/oss/phosphor/fosstars/data/AbstractCachingDataProvider.java: Some input files use unchecked or unsafe operations.
[INFO] ~/repos/fosstars-rating-core/src/main/java/com/sap/oss/phosphor/fosstars/data/AbstractCachingDataProvider.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- resources:3.3.1:testResources (default-testResources) @ fosstars-rating-core ---
[INFO] Copying 108 resources from src/test/resources to target/test-classes
[INFO] 
[INFO] --- compiler:3.11.0:testCompile (default-testCompile) @ fosstars-rating-core ---
[INFO] Changes detected - recompiling the module! :dependency
[INFO] Compiling 245 source files with javac [debug target 8] to target/test-classes
[WARNING] bootstrap class path not set in conjunction with -source 8
[WARNING] source value 8 is obsolete and will be removed in a future release
[WARNING] target value 8 is obsolete and will be removed in a future release
[WARNING] To suppress warnings about obsolete options, use -Xlint:-options.
[INFO] Annotation processing is enabled because one or more processors were found
  on the class path. A future release of javac may disable annotation processing
  unless at least one processor is specified by name (-processor), or a search
  path is specified (--processor-path, --processor-module-path), or annotation
  processing is enabled explicitly (-proc:only, -proc:full).
  Use -Xlint:-options to suppress this message.
  Use -proc:none to disable annotation processing.
[INFO] ~/repos/fosstars-rating-core/src/test/java/com/sap/oss/phosphor/fosstars/tool/format/MarkdownBuilderTest.java: Some input files use or override a deprecated API.
[INFO] ~/repos/fosstars-rating-core/src/test/java/com/sap/oss/phosphor/fosstars/tool/format/MarkdownBuilderTest.java: Recompile with -Xlint:deprecation for details.
[INFO] ~/repos/fosstars-rating-core/src/test/java/com/sap/oss/phosphor/fosstars/tool/GitHubProjectFinderTest.java: Some input files use unchecked or unsafe operations.
[INFO] ~/repos/fosstars-rating-core/src/test/java/com/sap/oss/phosphor/fosstars/tool/GitHubProjectFinderTest.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- surefire:3.1.2:test (default-test) @ fosstars-rating-core ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- jar:3.3.0:jar (default-jar) @ fosstars-rating-core ---
[INFO] Building jar: ~/repos/fosstars-rating-core/target/fosstars-rating-core-1.15.0-SNAPSHOT.jar
[INFO] 
[INFO] --- source:3.3.0:jar-no-fork (attach-sources) @ fosstars-rating-core ---
[INFO] Building jar: ~/repos/fosstars-rating-core/target/fosstars-rating-core-1.15.0-SNAPSHOT-sources.jar
[INFO] 
[INFO] --- javadoc:3.5.0:jar (attach-javadocs) @ fosstars-rating-core ---
[INFO] No previous run data found, generating javadoc.
[INFO] Building jar: ~/repos/fosstars-rating-core/target/fosstars-rating-core-1.15.0-SNAPSHOT-javadoc.jar
[INFO] 
[INFO] --- assembly:3.6.0:single (make-assembly) @ fosstars-rating-core ---
[INFO] Reading assembly descriptor: assembly.xml
[INFO] Building jar: ~/repos/fosstars-rating-core/target/fosstars-github-rating-calc.jar
[INFO] 
[INFO] --- checkstyle:3.1.2:checkstyle (validate) @ fosstars-rating-core ---
[WARNING] Old version of checkstyle detected. Consider updating to >= v8.30
[WARNING] For more information see: https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/upgrading-checkstyle.html
[INFO] Starting audit...
Audit done.
[INFO] 
[INFO] --- checkstyle:3.1.2:check (validate) @ fosstars-rating-core ---
[WARNING] Old version of checkstyle detected. Consider updating to >= v8.30
[WARNING] For more information see: https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/upgrading-checkstyle.html
[INFO] Starting audit...
Audit done.
[INFO] You have 0 Checkstyle violations.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  19.649 s
[INFO] Finished at: 2024-04-12T10:50:34+02:00
[INFO] ------------------------------------------------------------------------
```
</details>

<details>
    <summary>Running .jar file</summary>

```bash
TOKEN=xyz # use your personal token, see below
java -jar target/fosstars-github-rating-calc.jar --rating security --url https://github.com/curl/curl --verbose --token ${TOKEN}
```

```log
Exception in thread "main" java.lang.IllegalAccessError: class com.sap.oss.phosphor.fosstars.model.rating.example.SecurityRatingExample$Creator4JacksonDeserializer2d6e5330 tried to access method 'void com.sap.oss.phosphor.fosstars.model.rating.example.SecurityRatingExample.<init>()' (com.sap.oss.phosphor.fosstars.model.rating.example.SecurityRatingExample$Creator4JacksonDeserializer2d6e5330 is in unnamed module of loader com.fasterxml.jackson.module.afterburner.util.MyClassLoader @366c4480; com.sap.oss.phosphor.fosstars.model.rating.example.SecurityRatingExample is in unnamed module of loader 'app')
        at com.sap.oss.phosphor.fosstars.model.rating.example.SecurityRatingExample$Creator4JacksonDeserializer2d6e5330.createUsingDefault(com/sap/oss/phosphor/fosstars/model/rating/example/SecurityRatingExample$Creator4JacksonDeserializer.java)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:303)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:215)
        at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:120)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:170)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:136)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1296)
        at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3809)
        at com.sap.oss.phosphor.fosstars.model.RatingRepository.load(RatingRepository.java:285)
        at com.sap.oss.phosphor.fosstars.model.RatingRepository.securityRatingExample(RatingRepository.java:88)
        at com.sap.oss.phosphor.fosstars.model.RatingRepository.register(RatingRepository.java:199)
        at com.sap.oss.phosphor.fosstars.model.RatingRepository.<init>(RatingRepository.java:74)
        at com.sap.oss.phosphor.fosstars.model.RatingRepository.<clinit>(RatingRepository.java:63)
        at com.sap.oss.phosphor.fosstars.tool.OssProjectSecurityRatingHandler.<init>(OssProjectSecurityRatingHandler.java:52)
        at com.sap.oss.phosphor.fosstars.tool.Application.<init>(Application.java:100)
        at com.sap.oss.phosphor.fosstars.tool.Application.main(Application.java:85)
```
</details>

**Comment by skateball** [comment]
Not working with Java 17 / SapMachine 17.

Is there a reason why still Java 8 is used?
We hardly recommend to update to minimum Java 17-LTS or better Java 21-LTS

Afterwards please implement my PR #1000 

Best Regards Christian from SapMachine team
